FROM node:12.22.12-slim as build-stage
WORKDIR /app
COPY ./front-backOffice/package*.json ./
RUN npm install
COPY ./front-backOffice .
RUN npm run build -- --base-href /admin/

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist/front-backOffice /app/admin
COPY ./docker/resources/nginx.admin.conf /etc/nginx/conf.d/default.conf