FROM tiangolo/uwsgi-nginx-flask:python3.8

COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./backend .
COPY ./docker/resources/images /initial-photos