FROM tiangolo/uwsgi-nginx-flask:python3.8

COPY ./backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./backend .
RUN cp ./i18n/messages.pot.sample ./i18n/messages.pot && \
    cp ./i18n/fr/LC_MESSAGES/messages.mo.sample ./i18n/fr/LC_MESSAGES/messages.mo && \
    cp ./i18n/fr/LC_MESSAGES/messages.po.sample ./i18n/fr/LC_MESSAGES/messages.po
RUN pybabel compile -d ./i18n

COPY ./docker/images /data/