"""Observatory images

Revision ID: 33990994eeae
Revises: ba8ff1826771
Create Date: 2022-06-28 14:03:56.705384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33990994eeae'
down_revision = 'ba8ff1826771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_observatory', sa.Column('photo', sa.String(), nullable=True), schema='geopaysages')
    op.add_column('t_observatory', sa.Column('logo', sa.String(), nullable=True), schema='geopaysages')
    op.create_index('idx_t_observatory_geom', 't_observatory', ['geom'], unique=False, schema='geopaysages', postgresql_using='gist', postgresql_ops={})
    op.create_index('idx_t_site_geom', 't_site', ['geom'], unique=False, schema='geopaysages', postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_t_site_geom', table_name='t_site', schema='geopaysages', postgresql_using='gist', postgresql_ops={})
    op.drop_index('idx_t_observatory_geom', table_name='t_observatory', schema='geopaysages', postgresql_using='gist', postgresql_ops={})
    op.drop_column('t_observatory', 'logo', schema='geopaysages')
    op.drop_column('t_observatory', 'photo', schema='geopaysages')
    # ### end Alembic commands ###
