"""cor_roles_observatory

Revision ID: 5fd22937c0b5
Revises: d7fd422e1054
Create Date: 2025-04-30 15:02:58.652782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd22937c0b5'
down_revision = 'd7fd422e1054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cor_roles_observatory',
    sa.Column('id_role', sa.Integer(), nullable=False),
    sa.Column('id_observatory', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_observatory'], ['geopaysages.t_observatory.id'], ),
    sa.ForeignKeyConstraint(['id_role'], ['utilisateurs.t_roles.id_role'], ),
    sa.PrimaryKeyConstraint('id_role', 'id_observatory'),
    schema='geopaysages'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cor_roles_observatory', schema='geopaysages')
    # ### end Alembic commands ###
