"""site.main_observatory

Revision ID: 6443d436740a
Revises: d7b6052f4dad
Create Date: 2022-07-07 15:04:40.049161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6443d436740a'
down_revision = 'd7b6052f4dad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_site', sa.Column('main_theme_id', sa.Integer(), nullable=True), schema='geopaysages')
    op.create_foreign_key(None, 't_site', 'dico_theme', ['main_theme_id'], ['id_theme'], source_schema='geopaysages', referent_schema='geopaysages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_site', schema='geopaysages', type_='foreignkey')
    op.drop_column('t_site', 'main_theme_id', schema='geopaysages')
    # ### end Alembic commands ###
