"""Observatory

Revision ID: 9ec6b179f80a
Revises: ffd0e83f3c4c
Create Date: 2022-05-31 19:55:02.375742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec6b179f80a'
down_revision = 'ffd0e83f3c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_observatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'online', name='publishing_status'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='geopaysages'
    )
    op.add_column('t_site', sa.Column('id_observatory', sa.Integer(), nullable=True), schema='geopaysages')
    op.create_foreign_key('t_site_fk_observatory', 't_site', 't_observatory', ['id_observatory'], ['id'], source_schema='geopaysages', referent_schema='geopaysages')
    # ### end Alembic commands ###
    op.execute("INSERT INTO geopaysages.t_observatory (label, status) values ('Parc national de la Vanoise', 'online')")
    op.execute("UPDATE geopaysages.t_site set id_observatory = (SELECT id FROM geopaysages.t_observatory limit 1)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_site_fk_observatory', 't_site', schema='geopaysages', type_='foreignkey')
    op.drop_column('t_site', 'id_observatory', schema='geopaysages')
    op.drop_table('t_observatory', schema='geopaysages')
    # ### end Alembic commands ###
    op.execute("DROP TYPE publishing_status")
