"""Initial migration.

Revision ID: a84dc1367d9e
Revises: 
Create Date: 2022-05-31 12:17:47.618785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84dc1367d9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conf', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='geopaysages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conf', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='geopaysages')
    # ### end Alembic commands ###
