"""photo.id_observatory

Revision ID: d7b6052f4dad
Revises: 33990994eeae
Create Date: 2022-07-07 14:41:15.285056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b6052f4dad'
down_revision = '33990994eeae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_photo', sa.Column('id_observatory', sa.Integer(), nullable=True), schema='geopaysages')
    op.create_foreign_key(None, 't_photo', 't_observatory', ['id_observatory'], ['id'], source_schema='geopaysages', referent_schema='geopaysages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_photo', schema='geopaysages', type_='foreignkey')
    op.drop_column('t_photo', 'id_observatory', schema='geopaysages')
    # ### end Alembic commands ###
