"""Observatory

Revision ID: d8d449eefa0f
Revises: ffd0e83f3c4c
Create Date: 2022-06-02 08:11:40.570916

"""
from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


# revision identifiers, used by Alembic.
revision = 'd8d449eefa0f'
down_revision = 'ffd0e83f3c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_observatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('comparator', sa.Enum('sidebyside', 'split', name='comparator_enum'), nullable=True),
    sa.Column('geom', Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='geopaysages'
    )
    op.add_column('t_site', sa.Column('id_observatory', sa.Integer(), nullable=True), schema='geopaysages')
    op.create_foreign_key('t_site_fk_observatory', 't_site', 't_observatory', ['id_observatory'], ['id'], source_schema='geopaysages', referent_schema='geopaysages')
    # ### end Alembic commands ###
    coords = """
        6.58681072 45.18200501,
        6.73648285 45.23771352,
        6.88615497 45.18200501,
        6.8578211 45.29982259,
        6.97951588 45.38304217,
        6.81160717 45.40045984,
        6.73648285 45.50764377,
        6.66135852 45.40045984,
        6.49344982 45.38304217,
        6.61514459 45.29982259,
        6.58681072 45.18200501
    """
    t = {
        "title": "Parc national de la Vanoise", 
        "ref": "PNV",
        "color": "#b50000",
        "comparator": "split",
        "geom": "MULTIPOLYGON ((("+ coords +")))"
    }
    op.get_bind().execute(sa.sql.text("INSERT INTO geopaysages.t_observatory (title, ref, color, comparator, geom, is_published) "+
               "values (:title, :ref, :color, :comparator, :geom, true)"), **t)
    op.execute("UPDATE geopaysages.t_site set id_observatory = (SELECT id FROM geopaysages.t_observatory limit 1)")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('t_site_fk_observatory', 't_site', schema='geopaysages', type_='foreignkey')
    op.drop_column('t_site', 'id_observatory', schema='geopaysages')
    op.drop_table('t_observatory', schema='geopaysages')
    # ### end Alembic commands ###
    op.execute("DROP TYPE comparator_enum")
