"""empty message

Revision ID: f545b345135c
Revises: 6443d436740a
Create Date: 2022-07-11 08:07:37.574533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f545b345135c'
down_revision = '6443d436740a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_observatory', 'icon', schema='geopaysages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_observatory', sa.Column('icon', sa.VARCHAR(), autoincrement=False, nullable=True), schema='geopaysages')
    # ### end Alembic commands ###
