"""Initial migration.

Revision ID: ffd0e83f3c4c
Revises: 
Create Date: 2022-05-31 19:48:45.442620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffd0e83f3c4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    schema='geopaysages'
    )
    op.execute("INSERT INTO geopaysages.config (SELECT * from geopaysages.conf)")
    op.drop_table('conf', schema='geopaysages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conf',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    schema='geopaysages'
    )
    op.drop_table('config', schema='geopaysages')
    # ### end Alembic commands ###
